# Generated by Django 2.1.2 on 2018-10-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='play',
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
