# Generated by Django 2.1.2 on 2018-11-02 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0002_video_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='video',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
