# Generated by Django 2.1.2 on 2018-10-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20181029_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.FileField(upload_to='http://phazzg0m3.bkt.clouddn.com//media/'),
        ),
    ]
