# Generated by Django 2.1.2 on 2018-10-29 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20181029_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='url',
            new_name='rec',
        ),
    ]
