# Generated by Django 2.1.2 on 2018-10-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
