# Generated by Django 2.1.2 on 2018-10-31 05:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_followuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='following_users',
            field=models.ManyToManyField(related_name='follower_users', through='users.FollowUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
